### ISSUE TITLE
Adding a note section for every topic!

### ISSUE THREAD

**Issue by MohammadMarwan2005** [kamranahmedse/developer-roadmap#7225] opened 2024-09-25 04:15 UTC
### Feature Description

I think it will be a great idea to add a `Your Notes` section in every topic in any roadmap, for example: 

> Your Notes: `I learned the basics of this topic and will explore it more later'

> Your Notes: some_important_information_i_collected

Hope you like this idea and you will add it later, thank you!

**Comment by dansholds** [comment] 2024-09-25 10:05
dupe of #4566 & #5106

**Closed by dansholds** 2024-09-25 10:05 UTC
Labels: feature request
