### ISSUE TITLE
Add Babel to front end

### ISSUE THREAD

**Issue by mudenglong** [kamranahmedse/developer-roadmap#597] opened 2019-06-25 04:31 UTC
Babel, "the compiler for writing next-gen JS", isn't there! It's an important tool that you need to know. It should be under the "Front-end->Build Tools->Transpiler->Babel" section.

**Comment by Ronkiro** [comment] 2019-07-04 18:36
Dupe of #167

**Closed** 2019-07-04 18:55 UTC
