### ISSUE TITLE
PDF doesn't match what's on the screen

### ISSUE THREAD

**Issue by prafullkotecha** [kamranahmedse/developer-roadmap#4978] opened 2024-01-04 14:41 UTC
### What is the URL where the issue is happening

https://roadmap.sh/flutter

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Flutter Roadmap - Export to PDF generates a different roadmap than what's on the screen.
See attached PDF generated on Jan 4th, 2024
[flutter.pdf](https://github.com/kamranahmedse/developer-roadmap/files/13831216/flutter.pdf)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shreyash-01** [comment] 2024-01-09 12:14
Can you specify what are the things different?

**Comment by shreyash-01** [comment] 2024-01-28 11:33
Created a pull request  #5100 resolving this issue.

**Comment by dansholds** [comment] 2024-05-07 14:44
Duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/4358

**Closed by dansholds** 2024-05-07 14:44 UTC
Labels: bug
