### ISSUE TITLE
[Possible bug] Issues with links on the GraphQL roadmap

### ISSUE THREAD

**Issue by the-lazy-learner** [kamranahmedse/developer-roadmap#3246] opened 2023-01-06 04:53 UTC
On selecting items on the road map, I only see the item title, Mark as done option, and close option. The links to the resources are not properly visible. If there's a way I could help fix this, I'd love to be more involved. Here is a screenshot for reference on my phone.
![Screenshot_20230106-102247_Chrome.png](https://user-images.githubusercontent.com/13695177/210932631-e93653e8-e50f-4255-9706-6d844a00b904.png)

Thank you for curating such nice resources.

**Comment by bensonarafat** [comment] 2023-01-06 08:23
They are no content for graphQL
that's the cause.
It's not a bug.

**Comment by the-lazy-learner** [comment] 2023-01-06 08:28
Thank you! So, would it be possible for me to add resource links that seem related to the topics, so that somebody could probably review them and finally push upstream?

**Comment by bensonarafat** [comment] 2023-01-06 08:33
Yeah

**Comment by kamranahmedse** [comment] 2023-01-10 15:42
Closing as a non-issue. However, I have added the contribution text below the overlay to show that the page is in-progress with a link to folder where the content can be added. 

<img width="965" alt="image" src="https://user-images.githubusercontent.com/4921183/211595867-749fc4c6-5db6-43f7-9557-1dcc1d2fe73e.png">

**Closed by kamranahmedse** 2023-01-10 15:42 UTC
