### ISSUE TITLE
specific  content study

### ISSUE THREAD

**Issue by Eversea2017** [kamranahmedse/developer-roadmap#416] opened 2018-02-26 02:10 UTC
Hi，I really appreciate  Roadmap to becoming a web developer in 2018,  But there's only a route out it，
I wonder if you can give us some good study websites or documents about the route contents，THANKS

**Comment by Ronkiro** [comment] 2019-07-08 13:49
#560  is a dupe of this, but it has some more comments inside it.

Could this issue be closed in favor of #560?
@kamranahmedse ?

**Comment by kamranahmedse** [comment] 2019-07-10 06:41
Thanks @Ronkiro

**Closed** 2019-07-10 06:41 UTC
