### ISSUE TITLE
Accessebility for description tab

### ISSUE THREAD

**Issue by SaiAnveshReddy** [kamranahmedse/developer-roadmap#7059] opened 2024-09-09 17:10 UTC
### Feature Description

Lets say I am clicking on Introduction and a pop comes only on right side, it gets very uncomfotable to always keep my head towards right and read through entire detail description, if there is option to postion the component where I like would be suitable option, Thanks for letting me suggest

**Comment by kenshanta** [comment] 2024-09-09 17:35
Hey @SaiAnveshReddy thanks for bringing this up; however i believe it is a duplicate of the issue #6198 

Please close issue

**Closed** 2024-09-09 17:42 UTC
Labels: feature request
