### ISSUE TITLE
FEAT:: Note-Taking Functionality for Roadmaps

### ISSUE THREAD

**Issue by NamanAg0502** [kamranahmedse/developer-roadmap#6086] opened 2024-07-07 10:54 UTC
### Feature Description

**Summary**
Add a note-taking section to each roadmap, allowing users to add detailed comments or explanations without complicating the main roadmap structure.

**Motivation**
As a roadmap.sh user,
I want to be able to add notes or comments to my roadmaps, so that I can include additional information and personal insights without complicating the main roadmap structure.

**Proposed Solution**
Implement one or both of the following:
- A separate note-taking section associated with each roadmap
- The ability to add comments or notes to individual cards within the roadmap

**Comment by dansholds** [comment] 2024-07-07 13:03
Dupe of #6047

**Closed by dansholds** 2024-07-07 13:03 UTC
Labels: feature request
