### ISSUE TITLE
More accessibility 

### ISSUE THREAD

**Issue by Matheuscamartins2001** [kamranahmedse/developer-roadmap#5507] opened 2024-04-16 16:59 UTC
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

I would like more accessibility (mainly the responsiveness to screen readers for blind and visually impaired.)

Also, this seems to be an issue with all roadmaps, apparently they aren't in order. If it's not possible to solve the elementary navigate problem, can you guys please at least number the “steps" od the roadmaps in general? By doing this, the screen reader user wouldn't get lost

**Comment by kamranahmedse** [comment] 2024-05-11 13:28
Duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/5507

**Closed by kamranahmedse** 2024-05-11 13:28 UTC
Labels: suggestion, computer-science
