### ISSUE TITLE
Full stack Mobile Developer 

### ISSUE THREAD

**Issue by DaoHuyTuan** [kamranahmedse/developer-roadmap#117] opened 2017-04-05 05:47 UTC
i'm very sorry talk about a different tittle here . i'm a newbie  i like web develop but i'm studing about mobile developer , can you show me the way or anything i must learn about full stack mobile Developer 
thanks you for a great web developer map , it was helped me so much

**Comment by HenryTabima** [comment] 2017-04-08 01:47
actually i think it can be add to the roadmap like an aproach. web developers can program hibrid or bridged mobile apps. there are things like phonegap and ionic to hibrid apps and titanium or react native to bridged apps.

**Comment by damengilland** [comment] 2017-04-22 00:56
I made this comment in #127:

> We've got back-end and front-end... the concept of "full stack" is really dated, in my opinion. Everything now is complex enough to warrant specialization. And the concept of a "full stack engineer" usually means they can dabble, but aren't great at either. Usually. (=

**Comment by luchillo17** [comment] 2017-05-24 11:13
Dupe of https://github.com/kamranahmedse/developer-roadmap/issues/145?

**Comment by kamranahmedse** [comment] 2017-05-24 11:26
Closing for being duplicate

**Closed by kamranahmedse** 2017-05-24 11:26 UTC
