### ISSUE TITLE
Reset Filter State When Returning to Group View

### ISSUE THREAD

**Issue by Aj-Seven** [kamranahmedse/developer-roadmap#6533] opened 2024-08-13 08:13 UTC
### What is the URL where the issue is happening

https://roadmap.sh/roadmaps

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

**Description**

When navigating to a detailed view of a group and then returning to the main group view, the filter state does not reset correctly. As a result, previously applied filters may persist, leading to an incorrect display of groups. This issue affects the visibility of groups and their associated roadmaps.

**Problem**
   - Current Behavior: When a user selects a group and views its details, the `activeGroup` state is set. Returning to the main view does not reset the filter, so previously filtered groups might remain visible.
   - Expected Behavior: When returning to the main group view, all groups should be visible if no specific group is active. The `activeGroup` state should be cleared, and the `visibleGroups` should reset to include all groups.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment] 2024-08-15 01:28
I am not able to reproduce this so I am going to close it for now and put it in the backlog. 
Feel free to submit a PR if you can. Thank you!

**Closed by kamranahmedse** 2024-08-15 01:28 UTC
Labels: bug
