### ISSUE TITLE
Heaps

### ISSUE THREAD

**Issue by khansalmaan** [kamranahmedse/developer-roadmap#5984] opened 2024-06-30 13:05 UTC
### Roadmap URL

https://roadmap.sh/datastructures-and-algorithms

### Suggestions

I believe heaps should be included in any data structures roadmap because they are essential for priority queues, efficient sorting algorithms like heap sort, and optimizing various operations such as finding, inserting, and deleting elements. Heaps also play a key role in memory management and algorithm design, making them a fundamental concept for both practical and theoretical applications.

**Comment by dansholds** [comment] 2024-07-01 08:40
dupe of #5905

We have agreed to add this to the roadmap once it's migration to the new editor is complete. I will leave this issue open until them to prevent anyone else opening the same issue.

**Comment by Jash2606** [comment] 2024-07-26 16:04
Hey @dansholds,

I'm eager to start contributing to the project. Could you please assign me a task to get started?

**Comment by dansholds** [comment] 2024-09-09 13:55
heap sort is now in the roadmap.

**Closed by dansholds** 2024-09-09 13:55 UTC
Labels: datastructures-and-algorithms, reviewed
