### ISSUE TITLE
React-Native Download includes C++ roadmap

### ISSUE THREAD

**Issue by rabberdabber** [kamranahmedse/developer-roadmap#4795] opened 2023-11-30 07:33 UTC
### What is the URL where the issue is happening

https://roadmap.sh/react-native

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

While I download the React Native roadmap download, It includes C++ Road map so I thought it was a bug.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pirjademl** [comment] 2023-11-30 08:22
Hi kamran

I noticed the issue regarding the incorrect content in the React Native roadmap PDF #4795 I'm eager to contribute and would like to assist in resolving this.

After reviewing the details mentioned in the issue, I believe the solution involves replacing the current React Native PDF file in the public/PDFs directory with the accurate React Native roadmap content.

I'm ready to submit a pull request for this fix. If there are specific steps or additional information you'd like me to consider, please let me know.

Looking forward to collaborating on this!

Best regards,
Magdum

**Comment by sonvir249** [comment] 2023-12-26 12:57
This is a duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/4643

**Closed** 2024-01-09 12:00 UTC
Labels: bug
