### ISSUE TITLE
AppTelemetry - 404 Not Found Error 

### ISSUE THREAD

**Issue by erickmarx** [kamranahmedse/developer-roadmap#4223] opened 2023-07-17 17:54 UTC
### What is the URL where the issue is happening

https://roadmap.sh/devops

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Describe the Bug

When click open "AppTelemetry" on Devops roadmap, it stays in an infinite loading.
When it is closed, no other thread open on DevOps roadmap.

DevOps > AppTelemetry

Console panel show 404 not found error

### Output from browser console (if any)

http.6d2b195c.js:8     GET https://roadmap.sh/devops/monitoring/application-monitoring/app-dynamics 404
T @ http.6d2b195c.js:8
await in T (async)
rn @ http.6d2b195c.js:8
(anonymous) @ TopicDetail.276a3043.js:1
n @ TopicDetail.276a3043.js:1
handleSvgClick @ hoisted.d1c493fb.js:7

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by NabeelAhmed314** [comment] 2023-08-29 10:50
The issue is related to AppDynamics under Application Monitoring. When we click on AppDynamic it takes us to the following URL:

https://roadmap.sh/devops/monitoring/application-monitoring/app-dynamics

But the correct URL is as follows:

https://roadmap.sh/devops/application-monitoring/app-dynamics

This can be fixed in the JSON file, but we are not updating the JSON files due to implementing the Roadmap editor. One more thing that is not implemented correctly is when fetching topic detail, If we get an error we are setting the error to Topic not found but we are not hiding the loader and there is not content to be shown if some error occurs. Also, we are not resetting the error to empty due to which after an error occurs no new topic can be opened and it stays in the loading state.

I have tried an implementation for exception management that will notify the user of the issue and the user will be able to view other topics even when some topic has an issue.

Attached is a simple error message page.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/43681543/32efc797-67d5-402c-94d4-37083f268815)

**Comment by dansholds** [comment] 2024-05-07 14:21
The issue of endless loading on a "Topic not found" situation has been resolved.

Now when navigating to the DevOps roadmap[https://roadmap.sh/devops] Application Monitoring > AppDynamics, you will now see a "Topic Not Found" Message.

**Closed by dansholds** 2024-05-07 14:21 UTC
Labels: bug
