### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by AmirABody** [kamranahmedse/developer-roadmap#1792] opened 2022-09-18 15:03 UTC
You can add `pnpm` to Package Managers list in the FrontEnd Roadmap.

**Comment by kamranahmedse** [comment] 2022-09-18 16:25
Duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/1755

**Closed by kamranahmedse** 2022-09-18 16:25 UTC
