### ISSUE TITLE
Why is mobile application development *NOT* added to the front-end development?

### ISSUE THREAD

**Issue by mayur-novus** [kamranahmedse/developer-roadmap#170] opened 2017-05-25 04:31 UTC
Hi. I think you should also add mobile app development like Android, iOS and others too in the front-end development. It is also a user-facing development as well. I do not understand why that is ignored.

**Comment by garrettw** [comment] 2017-05-25 04:45
Duplicate of #145

**Closed** 2017-05-25 06:08 UTC
