### ISSUE TITLE
MLOPS course missing on coursera

### ISSUE THREAD

**Issue by sairamkumarm** [kamranahmedse/developer-roadmap#5839] opened 2024-06-08 16:41 UTC
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

The section pointing to Coursera for the MLOPS course goes to a 404 page

**Comment by kamranahmedse** [comment] 2024-06-08 17:07
Duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/5832

**Closed** 2024-06-08 17:07 UTC
Labels: topic-change, ai-data-scientist
