### ISSUE TITLE
Retitle "Server Side Game Developer" to "Game Network Programmer"

### ISSUE THREAD

**Issue by FilippoFederici** [kamranahmedse/developer-roadmap#5990] opened 2024-07-01 01:42 UTC
### Roadmap URL

https://roadmap.sh/server-side-game-developer

### Suggestions

The same argument expressed in #5989 applies. Beyond that, the proposed replacement, "Game Network Programmer", seems to be more common in job descriptions to express roles fitting the skills explored in the roadmap in subject. "Server Side", while still correct, seems to be less broad and target more specifically cases such as web games.

**Comment by dansholds** [comment] 2024-07-08 14:52
Closing as it's essentially a dupe of #5989

**Closed by dansholds** 2024-07-08 14:52 UTC
Labels: topic-change, server-side-game-developer
