### ISSUE TITLE
Add Android & iOS developement

### ISSUE THREAD

**Issue by sunguowei** [kamranahmedse/developer-roadmap#169] opened 2017-05-24 05:55 UTC

**Comment by luchillo17** [comment] 2017-05-24 11:13
Dupe of https://github.com/kamranahmedse/developer-roadmap/issues/145

**Comment by kamranahmedse** [comment] 2017-05-24 11:26
Thanks @luchillo17

**Closed by kamranahmedse** 2017-05-24 11:26 UTC

**Comment by sunguowei** [comment] 2017-05-25 05:57
🙂
