### ISSUE TITLE
devOps - Netdata in Monitoring

### ISSUE THREAD

**Issue by sivailango** [kamranahmedse/developer-roadmap#350] opened 2018-01-17 17:12 UTC
Why don't you add https://github.com/firehol/netdata in Monitoring and Alerting?

**Comment by Sanannasenzurella** [comment] 2018-02-08 09:47
Duplicate of #336

**Comment by kamranahmedse** [comment] 2020-01-18 08:16
This has been fixed and will be published in the coming release. Thank you 🙏

**Closed by kamranahmedse** 2020-01-18 08:16 UTC
